# Generated by Django 5.2.4 on 2025-08-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_end_date_customer_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='start_date',
        ),
    ]
